# You must restart the bot if you modify this file. If you use the web display of the history, don’t
# forget Hypercorn and/or Uvicorn.

mysqlclient:
  host:                   ""
  user:                   ""
  password:               ""
  database:               ""
  charset:                "utf8mb4"
  # Guarantee UTC regardless of server configuration
  init_command:           "SET time_zone = '+00:00'"

discord:
  bot_owner:              ""
  # Your Discord token. See https://discordpy.readthedocs.io/en/stable/discord.html
  token:                  ""
  bot_name:               "name for the bot to display in the history"
  server:                 id_server

mail:
  server:                 ""
  bot_address:            ""

users:
  db_table:               "project_users"

history:
  active:                 True/False
  db_table:               "project_history"
  storage_folder:         "/path/to/bot_files"
  storage_url:            "https://domain.tld/bot_files"

polls:
  db_table:               "project_polls"

irc:
  bot_owner:              ""
  server:                 "irc.libera.chat"
  nick:                   "MyBot"
  username:               "my_bot"
  real_name:              "My Bot"
  password:               ""
  quit_message:           "That’s the end of the beans"

irc_bridges:
  chan1:
    discord_chan:         id_chan
    # If you want messages on Discord displayed as coming from the users instead of the bot.
    # See https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks
    webhook: ""
  chan2:
    discord_chan:         id_chan
    webhook: ""
